apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supernode-database-pvc
  namespace: supernode
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
