apiVersion: v1
kind: Service
metadata:
  name: supernode-web-service
  namespace: supernode
  labels:
    app: supernode
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: supernode
