name: "Build image and upload to ghcr.io"

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**.md"
      - ".dockerignore"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build-image.yaml"

defaults:
  run:
    shell: "bash"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Docker: Setup Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Docker: Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: is pre-release
        id: is_pre_release
        run: |
          if [[ $(basename ${{ github.ref }}) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo prerelease=false | tee -a $GITHUB_OUTPUT
          else
            echo prerelease=true | tee -a $GITHUB_OUTPUT
          fi
  
      - name: "Docker: Metadata"
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ChingCdesu/supernode-server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ steps.is_pre_release.outputs.prerelease == 'false' }}
            type=raw,value=nightly,enable=${{ steps.is_pre_release.outputs.prerelease == 'true' }}
            type=ref,event=pr
            type=sha

      - name: "Docker: Build and Push Image"
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
